# Generated by Django 4.1.3 on 2023-03-03 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_initial"),
    ]

    operations = []
